original_repo: https://github.com/hackcu/live
title: HackCU LIVE
color: "#22292c"
secondary_color: "#22b573"

collections:
  sections:
    output: true
    permalink: /:path/

sass:
    sass_dir: assets/_sass
    style: compressed