original_repo: https://github.com/hackcu/live
title: Phase LIVE
color: "#011627"
secondary_color: "#ff9f1c"
devpost: https://phase.devpost.com

collections:
  sections:
    output: true
    permalink: /:path/

sass:
    sass_dir: assets/_sass
    style: compressed


# Countdown Timer
# Time format: "MONTH DAY YEAR HH:MM:SS TIMEZONE"
timer_enable: true
start_time: "November 10 2018 08:00:00 GMT-0700"
end_time: "November 10 2018 23:00:00 GMT-0700"
