original_repo: https://github.com/hackcu/live
title: HackCU V Live
color: "#22292c"
secondary_color: "#1AA8FF"
devpost: https://hackcuv.devpost.com/

collections:
  sections:
    output: true
    permalink: /:path/

sass:
    sass_dir: assets/_sass
    style: compressed

timezone: America/Denver

# Countdown Timer
# Time format: "MONTH DAY YEAR HH:MM:SS TIMEZONE"
timer_enable: true
start_time: "February 23 2019 12:00:00 GMT-0700"
end_time: "February 24 2019 12:00:00 GMT-0700"


# need to delete all of the non-needed prizes, etc....
